//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Mortara.Sepsis.Compute.ParameterConfig.XmlObjects {
    using System;
    using System.Xml.Serialization;


    /// <remarks/>
    [Serializable, XmlRoot("BucketData")]
    public partial class BucketData {
        
        private BucketSpec[] bucketsField;
        
        /// <remarks/>
        //[XmlElement("Buckets")]
        [XmlArray("Buckets")]
        [XmlArrayItem("BucketSpec")]
        public BucketSpec[] Buckets {
            get {
                return this.bucketsField;
            }
            set {
                this.bucketsField = value;
            }
        }
    }

    /// <remarks/>
    [Serializable]
    public partial class BucketSpec {
        
        private BucketType bucketTypeField;
        
        private int bucketNumberField;
        
        private string propertyNameField;

        [XmlElement(ElementName = "BucketType")]
        public BucketType BucketType {
            get {
                return this.bucketTypeField;
            }
            set {
                this.bucketTypeField = value;
            }
        }

        [XmlElement(ElementName = "BucketNumber")]
        public int BucketNumber {
            get {
                return this.bucketNumberField;
            }
            set {
                this.bucketNumberField = value;
            }
        }

        [XmlElement(ElementName = "PropertyName")]
        public string PropertyName {
            get {
                return this.propertyNameField;
            }
            set {
                this.propertyNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [Serializable]
    public enum BucketType {
        
        /// <remarks/>
        Max,
        
        /// <remarks/>
        Min,
        
        /// <remarks/>
        Mean,
    }
}
